name: petfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  custom_refresh_indicator: ^4.0.1
  dio: ^5.8.0+1
  easy_mask: ^2.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_modular: ^6.3.4
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  mime: ^2.0.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  path_provider_foundation: ^2.4.1
  scaffold_gradient_background: ^1.0.3+1
  shared_preferences: ^2.5.2
  signals: ^6.0.2
  signals_flutter: ^6.0.2
  toastification: ^3.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
